version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: runeshell
    main: ./cmd/runeshell
    binary: runeshell
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: runeshell
    builds:
      - runeshell
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - name: runeshell
    homepage: "https://github.com/ayush/Runeshell"
    description: "Tailnet-first remote terminal hub and agent"
    license: "MIT"
    tap:
      owner: ayush
      name: homebrew-tap
    commit_author:
      name: Ayush
      email: ayush@example.com
    folder: Formula
    install: |
      bin.install "runeshell"
    test: |
      system "#{bin}/runeshell", "version"
