name: Bug report
description: Report an issue with current behavior
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide minimal, repeatable steps.
      placeholder: |
        1. Run ...
        2. Open ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      description: Paste logs, errors, or screenshots when available.
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `runeshell version` or commit/tag
      placeholder: v0.1.0 or abc1234
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Go version, Node version, tmux version
      placeholder: macOS 14.4, go1.22.x, node 22.x, tmux 3.4
    validations:
      required: true
